language: "perl"
perl:
  - "5.16"
  - "5.10"
# There is little reason to have travis run multiple Perls.
#  - "5.14"
#  - "5.12"

before_install:
    - sudo apt-get install libgmp3-dev
    - sudo apt-get install libmpfr-dev
    - cpanm Test::Pod # optional dependency
    - cpanm Math::Prime::Util::GMP
    - cpanm Math::MPFR

env:
    -
    - MPU_NO_GMP=1
    - MPU_NO_MPFR=1
    - MPU_NO_GMP=1 MPU_NO_MPFR=1
    - MPU_NO_XS=1 MPU_NO_GMP=1 MPU_NO_MPFR=1


# Add the Travis mirror as well as another, because occasionally the Travis one gets confused.
install:
    - cpanm -v --installdeps --notest --mirror http://cpan.mirrors.travis-ci.org --mirror http://dl.ambiweb.de/mirrors/ftp.cpan.org --mirror http://cpan.cse.msu.edu .

script: "perl Makefile.PL; make test"
# branches:
#   only:
#     - master
notifications:
  recipients:
    - dana@acm.org
  email:
    on_success: change
    on_failure: always
#env:
