language: "perl"
perl:
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"

before_script:
#    - sudo apt-get install libgmp3-dev
#    - cpanm Test::Pod # optional dependency
    - sudo apt-get install libmpfr-dev
    - cpanm Math::Prime::Util::GMP
    - cpanm Math::MPFR

env:
    - MPU_NO_XS=1 MPU_NO_GMP=1 MPU_NO_MPFR=1
    - MPU_NO_MPFR=1
    - MPU_NO_GMP=1
    - MPU_NO_GMP=1 MPU_NO_MPFR=1


install:
    - cpanm -v --installdeps --notest --mirror http://cpan.mirrors.travis-ci.org .

script: "perl Makefile.PL; make test"
# branches:
#   only:
#     - master
notifications:
  recipients:
    - dana@acm.org
  email:
    on_success: change
    on_failure: always
#env:
